//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetrieveTwitterFeeds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tweets
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public string StatusID { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string Query { get; set; }
        public string Language { get; set; }
        public string TweetLink { get; set; }
        public string Username { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateInsertedInDB { get; set; }
    }
}
